version: '3.7'

services:
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile.prod
    expose:
      - 4200
    volumes: 
      - frontend_static:/app/dist
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - database
  database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod.pgadmin
    volumes:
      - pgadmin:/root/.pgadmin
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
      - frontend_static:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - backend
      - pgadmin
volumes:
  pgadmin:
  postgres_data:
  static_volume:
  media_volume:
  frontend_static: